import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class AddCencus extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/barangay_db2";
    String username = "root";
    String password = "";
    
    public AddCencus() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Add");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MaleTextField = new javax.swing.JTextField();
        YearTextField = new javax.swing.JTextField();
        FemaleTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        DateTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("BARANGAY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, -1, -1));

        jLabel2.setText("MALE COUNT:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel3.setText("YEAR:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setText("FEMALE COUNT:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        MaleTextField.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jPanel1.add(MaleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 120, 30));

        YearTextField.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jPanel1.add(YearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        FemaleTextField.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jPanel1.add(FemaleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 30));

        AddButton.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        CancelButton.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        DateTextField.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jPanel1.add(DateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, 30));

        jLabel5.setText("DATE RECORDED:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
    String dateRecorded = DateTextField.getText(); // Assuming it's in the format YYYY-MM-DD
    String maleCountStr = MaleTextField.getText();
    String femaleCountStr = FemaleTextField.getText();

    if (dateRecorded.isEmpty() || maleCountStr.isEmpty() || femaleCountStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all fields.");
        return;
    }

    try {
        // Convert to integers
        int maleCount = Integer.parseInt(maleCountStr);
        int femaleCount = Integer.parseInt(femaleCountStr);
        int totalPopulation = maleCount + femaleCount; // Calculate total population
        
        // Extract year from dateRecorded as an integer
        int year = Integer.parseInt(dateRecorded.substring(0, 4));

        // Ensure dateRecorded is stored without time (format: YYYY-MM-DD)
        String formattedDateRecorded = dateRecorded.split(" ")[0];

        // Establish database connection
        try (Connection conn = DriverManager.getConnection(url, username, password)) {
            // SQL Insert query (Added total_population column)
            String query = "INSERT INTO census (date_recorded, male_population, female_population, total_population, year) VALUES (?, ?, ?, ?, ?)";

            // Prepare the statement
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, formattedDateRecorded);
            pst.setInt(2, maleCount);
            pst.setInt(3, femaleCount);
            pst.setInt(4, totalPopulation);
            pst.setInt(5, year);

            // Execute the query
            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Census data added successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Error adding data.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numeric values for Male Count and Female Count.");
    }

    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
        CencusFrame cencusFrame = new CencusFrame();
        cencusFrame.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCencus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCencus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCencus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCencus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCencus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JTextField FemaleTextField;
    private javax.swing.JTextField MaleTextField;
    private javax.swing.JTextField YearTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
